DROP TABLE IF EXISTS TBL_DRONE;
DROP TABLE IF EXISTS TBL_MEDICATION;

CREATE TABLE TBL_DRONE(
    ID INT PRIMARY KEY AUTO_INCREMENT(20),
    SERIAL_NUMBER VARCHAR(100),
    MODEL VARCHAR(100),
    WEIGHT_LIMIT DOUBLE,
    BATTERY_CAPACITY DOUBLE,
    STATE VARCHAR,
    CHECK (model IN ('Lightweight', 'Middleweight', 'Cruiserweight', 'Heavyweight')),
    CHECK (state IN ('IDLE', 'LOADING', 'LOADED', 'DELIVERING', 'DELIVERED', 'RETURNING'))
);

CREATE TABLE TBL_MEDICATION(
    ID INT PRIMARY KEY AUTO_INCREMENT(20),
    NAME VARCHAR(100),
    WEIGHT DOUBLE,
    CODE VARCHAR(100),
    IMAGE VARCHAR(2048),
    CHECK (name REGEXP '^[a-zA-Z0-9_-]+$'),
    CHECK (code REGEXP '^[A-Z0-9_]+$')
);




