DROP TABLE IF EXISTS TBL_DRONE;

CREATE TABLE TBL_DRONE(
    ID INT PRIMARY KEY,
    SERIAL_NUMBER VARCHAR(100),
    MODEL VARCHAR(100),
    WEIGHT_LIMIT DOUBLE,
    BATTERY_CAPACITY DOUBLE,
    STATE VARCHAR
);

INSERT INTO TBL_DRONE (ID, SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE)
VALUES
  (1, 'ABCD1234', 'Mavic Air', 2.0, 30.0, 'AVAILABLE'),
  (2, 'EFGH5678', 'Phantom 4 Pro', 4.0, 28.0, 'IN_USE'),
  (3, 'IJKL9012', 'Mavic 2 Pro', 2.0, 31.0, 'AVAILABLE');
 COMMIT;



